server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    url: jdbc:h2:mem:desafio
    driverClassName: org.h2.Driver
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  batch:
    jdbc:
      initialize-schema: always
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
client:
  applicationName: VALIDA-CPF
  url:
    cpf: https://user-info.herokuapp.com/users
    
swagger:
  base-package: com.desafio
  title: Desafio Técnico CWI
  description: Documentação do serviço
  version: 1.0
  terms: Termos de Serviço
  develloper-name: Alexandre Oliveira
  develloper-email: alexandre.cgpb.df@gmail.com
  licence: Apache License Version 2.0
  licence-url: https://www.apache.org/licesen.html